version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      root-development-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /worker
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      worker-development-dependencies:
        dependency-type: development
